# schema.yml
version: 2

sources:
  - name: gz_raw_data
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "Greenweez'in satışları / her orders_id'de bulunan bir product_id için bir satırımız var"
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}
        columns:
          - name: date_date
            description: "satın alma tarihi"
          - name: orders_id
            description: "foreign key to ship"
            tests:
              - not_null
          - name: pdt_id
            description: "foreign key to product"
            tests:
              - not_null
          - name: revenue
            description: "quantity*selling_price (amount of payment by customer)"
          - name: quantity
            description: "quantity of the product purchased by customer for a given order"
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - orders_id
                - pdt_id
      - name: product
        identifier: raw_gz_product
        description: "Product of Greenweez"
        columns:
          - name: products_id
            description: "Primary key"
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: "Price of the product"
      - name: ship
        identifier: raw_gz_ship
        description: "shipping data for Greenweez orders"
        columns:
          - name: orders_id
            description: "Primary key"
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: "Amount of payment for order for shipping by customer"
          - name: logCost
            description: "the cost of preparing the parcel in the distribution centre/warehouse"
          - name: ship_cost
            description: "shipping cost paid by Greenweez to the carrier/logistics provider"